### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by lord-i-will** [WHU-AISE/TVDiag#1]
run 'pip install -r requirements.txt', some error occurred. It seemed like Python version incompatible. Which version do you use?
My version: MacOS
```bash
pip -V
pip 24.2 from /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip (python 3.12)
```

The errors occurred:
```bash
pip install -r requirements.txt
Looking in indexes: https://bytedpypi.byted.org/simple/
Collecting matplotlib==3.2.2 (from -r requirements.txt (line 1))
  Using cached https://bytedpypi.byted.org/packages/matplotlib/matplotlib-3.2.2.tar.gz (40.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      /private/var/folders/xk/kb6ffpnx2yd9yzc61f3n89hm0000gp/T/pip-install-m9i0ytlk/matplotlib_d3b5dc705b3546ec883c9eab93436851/setup.py:33: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              By 2024-Nov-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************

      !!
        from setuptools.command.test import test as TestCommand
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/xk/kb6ffpnx2yd9yzc61f3n89hm0000gp/T/pip-install-m9i0ytlk/matplotlib_d3b5dc705b3546ec883c9eab93436851/setup.py", line 52, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/xk/kb6ffpnx2yd9yzc61f3n89hm0000gp/T/pip-install-m9i0ytlk/matplotlib_d3b5dc705b3546ec883c9eab93436851/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/xk/kb6ffpnx2yd9yzc61f3n89hm0000gp/T/pip-install-m9i0ytlk/matplotlib_d3b5dc705b3546ec883c9eab93436851/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/xk/kb6ffpnx2yd9yzc61f3n89hm0000gp/T/pip-install-m9i0ytlk/matplotlib_d3b5dc705b3546ec883c9eab93436851/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by theoryXie** [comment]
We deprecate the requirements.txt and paste our dependencies in README.md
